### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by LorenzoHEH** [dubmart/OpenClassroomProject#1]
Bonjour,

Quel est votre but final pour ce projet ? un site E-commerce, une application web ?

Bien à vous
LorenzoHEH

**Comment by dubmart** [comment]
Bonjour c'est un projet privé de la plus haute importance.

Bien à Vous

**Comment by LorenzoHEH** [comment]
Pourquoi votre projet est il en publique alors ?

**Comment by dubmart** [comment]
Car je n'ai pas la version privée, qui est payante
